MODEL_NAME = $(notdir {{.hugginface_model_id}})

deploy_and_run:
	databricks bundle deploy --profile $(PROFILE)
	databricks bundle run deepseek_r1_deployment_job  --profile $(PROFILE)

destroy_and_delete:
	databricks bundle destroy --profile $(PROFILE)
	databricks serving-endpoints delete $(MODEL_NAME) --profile $(PROFILE)